baseURL = "https://kaszkowiak.org/"

theme = "kaszkowiak"
title = "Maciej Kaszkowiak"
defaultContentLanguage = "pl"
timeout = "120s"

[languages]
	[languages.pl]
		languageCode = "pl-PL"
		languageName = "Polski"
		weight = 1
		[languages.pl.params]
			description = "Portfolio Macieja Kaszkowiaka"
			locale = "pl_PL"
	[languages.en]
		languageCode = "en"
		languageName = "English"
		weight = 2 
		[languages.en.params]
			description = "Maciej Kaszkowiak's portfolio"
			locale = "en"

[params]
	author = "Maciej Kaszkowiak"
	sitename = "kaszkowiak.org"

[taxonomies]
	tag = "tags"

[imaging]
	[imaging.exif]
		includeFields = "Orientation"

[markup.highlight]
	style = "emacs"